apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moj-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moj-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moja-aplikacja
  template:
    metadata:
      labels:
        app: moja-aplikacja
    spec:
      containers:
      - name: moj-kontener
        image: moj-obraz:latest
        volumeMounts:
        - name: moj-persistent-volume
          mountPath: /moje-dane
  volumes:
    - name: moj-persistent-volume
      persistentVolumeClaim:
        claimName: moj-pvc

